//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADP.DS.FrontOffice.FI.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetail
    {
        public int ProductDetailId { get; set; }
        public int DealerId { get; set; }
        public int ProductId { get; set; }
        public int ProductTypeId { get; set; }
        public string ProductType { get; set; }
        public int ProviderId { get; set; }
        public string ProviderName { get; set; }
        public string ProductName { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        public string VideoUrl { get; set; }
        public bool CashType { get; set; }
    }
}
