
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ADP.DS.FrontOffice.FI.EF
{

using System;
    using System.Collections.Generic;
    
public partial class ProductSaleStats
{

    public int StatisticId { get; set; }

    public int DealerId { get; set; }

    public string ProductType { get; set; }

    public Nullable<int> NumberOfProductsSold { get; set; }

}

}
